---
title: "R Notebook"
output: html_notebook
加载包
```{r}
library(tidyverse)
install.packages("here") #记得加引号
library(here)
```
1.读取数据
```{r}
readLines(here("data","sub01.log"))%>% #这个是管道操作。
str_detect("RT")%>%
which()
#先按行读取 然后分出两个表来  确定各自的起始，再依次读取。
#对文本信息进行定位，确定要寻找的内容
#stringr 处理字符串的  在tidyverse里面
readLines(here("data","sub01.log"))%>% #这个是管道操作。
str_detect("RT")%>%
which()->table2_start

readLines(here("data","sub01.log"))%>% #这个是管道操作。
str_detect("Subject")%>%
which()->table1_start

table1_end<-table2_start-2
table2_end<-length(readLines(here("data","sub01.log")))

raw_text<-readLines(here("data","sub01.log"))
writeLines(raw_text[table1_start:table1_end],here("output","sub01.table1.txt"))

#如果人肉循环的话  就是把sub01换成02  再往下一直
#但我们希望这个能够智能化做 所以  要把这一块的函数封装   自己往下走循环
#先完成函数操作  再把函数里面不变的部分写进方括号  再把变得部分写进前面varibles的括号里面
#再给他们起个函数名

convert_logfile<-function(filename,output_name){
readLines(here("data",filename))%>% #这个是管道操作。
str_detect("RT")%>%
which()->table2_start
readLines(here("data",filename))%>% #这个是管道操作。
str_detect("Subeject")%>%
which()->table1_start
table1_end<-table2_start-2
table2_end<-length(readLines(here("data","filename")))
raw_text<-readLines(here("data","filename"))
writeLines(raw_text[table1_start:table1_end], here("output", output_name))
}
#开始写循环
convert_logfile("sub02.log","sub02.table2.txt")
subs<-c("sub01","sub02")
for(i in subs){
  filename<-paste0(i,".log")
  output_name<-paste0(i,".table1_new.txt")
 covert_logfile(filename,output_name)
  }
```


